### PR TITLE
These lines were incorrectly indented causing them to not be considered ...

### PR DESCRIPTION
**Pull request by yamatt**
...lines of code

Added correct indentation (relative to bullet).

### CODE REVIEW

**Comment by strugee** [comment]
@yamatt nice catch! Can you:

1. Rebase your commit on top of current `master`?
2. Fix some of the other indentation problems, if you have time?
3. Modify your commit message so it conforms to git conventions? See http://chris.beams.io/posts/git-commit/

If you need help with any of these, I'd be happy to help you out. Alternately if you click the "allow edits from maintainers" checkbox in the sidebar, I _think_ that should allow me to push to your branch and make these changes myself.

Thanks!

**Comment by yamatt** [comment]
Hi @strugee, considering this was over 3 years ago I don't really have the environment set up to get this all fixed for you at the moment. I hope you don't mind if I hand it back to you.

**Comment by strugee** [comment]
@yamatt not a problem, thanks for giving me write access!

**Comment by strugee** [comment]
@yamatt looks like this was actually fixed in `master` a while ago. Thanks so much for your patch though! :)

**Pull request closed without merging**
